### ISSUE TITLE
Country_lord

### ISSUE THREAD

**Issue by salvoronis** [Avvessalom/ITMO-Information-Systems-and-Databases-Course-Project#1]
Почему Country_lord не ссылается на citizen? И аналогично почему ниндзя не ссылаются на citizen? Они же тоже граждане просто с расширенной таблицей

**Comment by Avvessalom** [comment]
потому-что под гражданином подразумеваются обычные микрочелы, а ниндзя необычные.
А вот с `Country_lord` косяк, согласен
